/*
 * ENUMERATION DES SPECIALITES TROUVEES DANS LE CHU PRINCETON PLAINSBORO
 */
package princetonPlainsboro;

/**
 *
 * @author dasilvae
 */
public enum Specialite {
    ANESTHESIOLOGIE, 
    CARDIOLOGIE, 
    DERMATOLOGIE, 
    GERONTOLOGIE, 
    GYNECOLOGIE, 
    HEMATOLOGIE, 
    NEUROLOGIE, 
    PEDIATRIE, 
    RADIOLOGIE, 
    UROLOGIE, 
    ONCOLOGIE, 
    ORTHODONTIE,
    AUTRE ;
}
